/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlockType = IDL.Variant({
  'Playlist' : IDL.Null,
  'Single' : IDL.Null,
});
export const CalendarEvent = IDL.Record({
  'scheduledDate' : IDL.Int,
  'blockType' : BlockType,
  'taskId' : IDL.Nat,
  'trackPosition' : IDL.Nat,
});
export const Session = IDL.Record({
  'totalTracks' : IDL.Nat,
  'startedAt' : IDL.Int,
  'pauseCount' : IDL.Nat,
  'endedAt' : IDL.Opt(IDL.Int),
  'tracksCompleted' : IDL.Nat,
  'playlistId' : IDL.Text,
  'score' : IDL.Nat,
  'taskId' : IDL.Nat,
  'playlistName' : IDL.Text,
  'completedWithinSession' : IDL.Bool,
});
export const TaskState = IDL.Variant({
  'Overtime' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
  'NotStarted' : IDL.Null,
});
export const Priority = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
  'Urgent' : IDL.Null,
});
export const Task = IDL.Record({
  'effortTracks' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'deadline' : IDL.Opt(IDL.Int),
  'state' : TaskState,
  'notes' : IDL.Opt(IDL.Text),
  'priority' : Priority,
});
export const UserProfile = IDL.Record({
  'spotifyConnected' : IDL.Bool,
  'name' : IDL.Text,
});
export const SpotifyTokens = IDL.Record({
  'expiresAt' : IDL.Int,
  'refreshToken' : IDL.Text,
  'displayName' : IDL.Text,
  'spotifyUserId' : IDL.Text,
  'accessToken' : IDL.Text,
});
export const WorkloadConfig = IDL.Record({
  'workEndHour' : IDL.Nat,
  'workStartHour' : IDL.Nat,
  'dailyTrackCapacity' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCalendarEvent' : IDL.Func([CalendarEvent], [IDL.Nat], []),
  'createSession' : IDL.Func([Session], [IDL.Nat], []),
  'createTask' : IDL.Func([Task], [IDL.Nat], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentlyPlaying' : IDL.Func([], [IDL.Text], []),
  'getPlaybackState' : IDL.Func([], [IDL.Text], []),
  'getUserPlaylists' : IDL.Func([], [IDL.Text], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTokens' : IDL.Func([], [IDL.Opt(SpotifyTokens)], ['query']),
  'getWorkloadConfig' : IDL.Func([], [WorkloadConfig], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'pausePlayback' : IDL.Func([], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startPlayback' : IDL.Func([], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateSession' : IDL.Func([IDL.Nat, Session], [], []),
  'updateTask' : IDL.Func([IDL.Nat, Task], [], []),
  'updateUserTokens' : IDL.Func([SpotifyTokens], [], []),
  'updateWorkloadConfig' : IDL.Func([WorkloadConfig], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlockType = IDL.Variant({ 'Playlist' : IDL.Null, 'Single' : IDL.Null });
  const CalendarEvent = IDL.Record({
    'scheduledDate' : IDL.Int,
    'blockType' : BlockType,
    'taskId' : IDL.Nat,
    'trackPosition' : IDL.Nat,
  });
  const Session = IDL.Record({
    'totalTracks' : IDL.Nat,
    'startedAt' : IDL.Int,
    'pauseCount' : IDL.Nat,
    'endedAt' : IDL.Opt(IDL.Int),
    'tracksCompleted' : IDL.Nat,
    'playlistId' : IDL.Text,
    'score' : IDL.Nat,
    'taskId' : IDL.Nat,
    'playlistName' : IDL.Text,
    'completedWithinSession' : IDL.Bool,
  });
  const TaskState = IDL.Variant({
    'Overtime' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
    'NotStarted' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
    'Urgent' : IDL.Null,
  });
  const Task = IDL.Record({
    'effortTracks' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'deadline' : IDL.Opt(IDL.Int),
    'state' : TaskState,
    'notes' : IDL.Opt(IDL.Text),
    'priority' : Priority,
  });
  const UserProfile = IDL.Record({
    'spotifyConnected' : IDL.Bool,
    'name' : IDL.Text,
  });
  const SpotifyTokens = IDL.Record({
    'expiresAt' : IDL.Int,
    'refreshToken' : IDL.Text,
    'displayName' : IDL.Text,
    'spotifyUserId' : IDL.Text,
    'accessToken' : IDL.Text,
  });
  const WorkloadConfig = IDL.Record({
    'workEndHour' : IDL.Nat,
    'workStartHour' : IDL.Nat,
    'dailyTrackCapacity' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCalendarEvent' : IDL.Func([CalendarEvent], [IDL.Nat], []),
    'createSession' : IDL.Func([Session], [IDL.Nat], []),
    'createTask' : IDL.Func([Task], [IDL.Nat], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentlyPlaying' : IDL.Func([], [IDL.Text], []),
    'getPlaybackState' : IDL.Func([], [IDL.Text], []),
    'getUserPlaylists' : IDL.Func([], [IDL.Text], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTokens' : IDL.Func([], [IDL.Opt(SpotifyTokens)], ['query']),
    'getWorkloadConfig' : IDL.Func([], [WorkloadConfig], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'pausePlayback' : IDL.Func([], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startPlayback' : IDL.Func([], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateSession' : IDL.Func([IDL.Nat, Session], [], []),
    'updateTask' : IDL.Func([IDL.Nat, Task], [], []),
    'updateUserTokens' : IDL.Func([SpotifyTokens], [], []),
    'updateWorkloadConfig' : IDL.Func([WorkloadConfig], [], []),
  });
};

export const init = ({ IDL }) => { return []; };