/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BlockType = { 'Playlist' : null } |
  { 'Single' : null };
export interface CalendarEvent {
  'scheduledDate' : bigint,
  'blockType' : BlockType,
  'taskId' : bigint,
  'trackPosition' : bigint,
}
export type Priority = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null } |
  { 'Urgent' : null };
export interface Session {
  'totalTracks' : bigint,
  'startedAt' : bigint,
  'pauseCount' : bigint,
  'endedAt' : [] | [bigint],
  'tracksCompleted' : bigint,
  'playlistId' : string,
  'score' : bigint,
  'taskId' : bigint,
  'playlistName' : string,
  'completedWithinSession' : boolean,
}
export interface SpotifyTokens {
  'expiresAt' : bigint,
  'refreshToken' : string,
  'displayName' : string,
  'spotifyUserId' : string,
  'accessToken' : string,
}
export interface Task {
  'effortTracks' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'deadline' : [] | [bigint],
  'state' : TaskState,
  'notes' : [] | [string],
  'priority' : Priority,
}
export type TaskState = { 'Overtime' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null } |
  { 'NotStarted' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'spotifyConnected' : boolean, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkloadConfig {
  'workEndHour' : bigint,
  'workStartHour' : bigint,
  'dailyTrackCapacity' : bigint,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCalendarEvent' : ActorMethod<[CalendarEvent], bigint>,
  'createSession' : ActorMethod<[Session], bigint>,
  'createTask' : ActorMethod<[Task], bigint>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAllSessions' : ActorMethod<[], Array<Session>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentlyPlaying' : ActorMethod<[], string>,
  'getPlaybackState' : ActorMethod<[], string>,
  'getUserPlaylists' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTokens' : ActorMethod<[], [] | [SpotifyTokens]>,
  'getWorkloadConfig' : ActorMethod<[], WorkloadConfig>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'pausePlayback' : ActorMethod<[], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startPlayback' : ActorMethod<[], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateSession' : ActorMethod<[bigint, Session], undefined>,
  'updateTask' : ActorMethod<[bigint, Task], undefined>,
  'updateUserTokens' : ActorMethod<[SpotifyTokens], undefined>,
  'updateWorkloadConfig' : ActorMethod<[WorkloadConfig], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];