/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WorkloadConfig {
    workEndHour: bigint;
    workStartHour: bigint;
    dailyTrackCapacity: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface SpotifyTokens {
    expiresAt: bigint;
    refreshToken: string;
    displayName: string;
    spotifyUserId: string;
    accessToken: string;
}
export interface Task {
    effortTracks: bigint;
    name: string;
    createdAt: bigint;
    deadline?: bigint;
    state: TaskState;
    notes?: string;
    priority: Priority;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Session {
    totalTracks: bigint;
    startedAt: bigint;
    pauseCount: bigint;
    endedAt?: bigint;
    tracksCompleted: bigint;
    playlistId: string;
    score: bigint;
    taskId: bigint;
    playlistName: string;
    completedWithinSession: boolean;
}
export interface CalendarEvent {
    scheduledDate: bigint;
    blockType: BlockType;
    taskId: bigint;
    trackPosition: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface UserProfile {
    spotifyConnected: boolean;
    name: string;
}
export enum BlockType {
    Playlist = "Playlist",
    Single = "Single"
}
export enum Priority {
    Low = "Low",
    High = "High",
    Medium = "Medium",
    Urgent = "Urgent"
}
export enum TaskState {
    Overtime = "Overtime",
    InProgress = "InProgress",
    Completed = "Completed",
    NotStarted = "NotStarted"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCalendarEvent(event: CalendarEvent): Promise<bigint>;
    createSession(session: Session): Promise<bigint>;
    createTask(task: Task): Promise<bigint>;
    deleteTask(id: bigint): Promise<void>;
    getAllSessions(): Promise<Array<Session>>;
    getAllTasks(): Promise<Array<Task>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentlyPlaying(): Promise<string>;
    getPlaybackState(): Promise<string>;
    getUserPlaylists(): Promise<string>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserTokens(): Promise<SpotifyTokens | null>;
    getWorkloadConfig(): Promise<WorkloadConfig>;
    isCallerAdmin(): Promise<boolean>;
    pausePlayback(): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    startPlayback(): Promise<string>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateSession(id: bigint, session: Session): Promise<void>;
    updateTask(id: bigint, task: Task): Promise<void>;
    updateUserTokens(tokens: SpotifyTokens): Promise<void>;
    updateWorkloadConfig(config: WorkloadConfig): Promise<void>;
}
import type { BlockType as _BlockType, CalendarEvent as _CalendarEvent, Priority as _Priority, Session as _Session, SpotifyTokens as _SpotifyTokens, Task as _Task, TaskState as _TaskState, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCalendarEvent(arg0: CalendarEvent): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCalendarEvent(to_candid_CalendarEvent_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCalendarEvent(to_candid_CalendarEvent_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSession(arg0: Session): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(to_candid_Session_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(to_candid_Session_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTask(arg0: Task): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(to_candid_Task_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(to_candid_Task_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getAllSessions(): Promise<Array<Session>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSessions();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSessions();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentlyPlaying(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentlyPlaying();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentlyPlaying();
            return result;
        }
    }
    async getPlaybackState(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlaybackState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlaybackState();
            return result;
        }
    }
    async getUserPlaylists(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPlaylists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPlaylists();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTokens(): Promise<SpotifyTokens | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTokens();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTokens();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkloadConfig(): Promise<WorkloadConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkloadConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkloadConfig();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async pausePlayback(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.pausePlayback();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pausePlayback();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async startPlayback(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.startPlayback();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startPlayback();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateSession(arg0: bigint, arg1: Session): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSession(arg0, to_candid_Session_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSession(arg0, to_candid_Session_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTask(arg0: bigint, arg1: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, to_candid_Task_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, to_candid_Task_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateUserTokens(arg0: SpotifyTokens): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserTokens(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserTokens(arg0);
            return result;
        }
    }
    async updateWorkloadConfig(arg0: WorkloadConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkloadConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkloadConfig(arg0);
            return result;
        }
    }
}
function from_candid_Priority_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Session_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Session): Session {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_TaskState_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskState): TaskState {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SpotifyTokens]): SpotifyTokens | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalTracks: bigint;
    startedAt: bigint;
    pauseCount: bigint;
    endedAt: [] | [bigint];
    tracksCompleted: bigint;
    playlistId: string;
    score: bigint;
    taskId: bigint;
    playlistName: string;
    completedWithinSession: boolean;
}): {
    totalTracks: bigint;
    startedAt: bigint;
    pauseCount: bigint;
    endedAt?: bigint;
    tracksCompleted: bigint;
    playlistId: string;
    score: bigint;
    taskId: bigint;
    playlistName: string;
    completedWithinSession: boolean;
} {
    return {
        totalTracks: value.totalTracks,
        startedAt: value.startedAt,
        pauseCount: value.pauseCount,
        endedAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.endedAt)),
        tracksCompleted: value.tracksCompleted,
        playlistId: value.playlistId,
        score: value.score,
        taskId: value.taskId,
        playlistName: value.playlistName,
        completedWithinSession: value.completedWithinSession
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    effortTracks: bigint;
    name: string;
    createdAt: bigint;
    deadline: [] | [bigint];
    state: _TaskState;
    notes: [] | [string];
    priority: _Priority;
}): {
    effortTracks: bigint;
    name: string;
    createdAt: bigint;
    deadline?: bigint;
    state: TaskState;
    notes?: string;
    priority: Priority;
} {
    return {
        effortTracks: value.effortTracks,
        name: value.name,
        createdAt: value.createdAt,
        deadline: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.deadline)),
        state: from_candid_TaskState_n22(_uploadFile, _downloadFile, value.state),
        notes: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.notes)),
        priority: from_candid_Priority_n25(_uploadFile, _downloadFile, value.priority)
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Overtime: null;
} | {
    InProgress: null;
} | {
    Completed: null;
} | {
    NotStarted: null;
}): TaskState {
    return "Overtime" in value ? TaskState.Overtime : "InProgress" in value ? TaskState.InProgress : "Completed" in value ? TaskState.Completed : "NotStarted" in value ? TaskState.NotStarted : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} | {
    Urgent: null;
}): Priority {
    return "Low" in value ? Priority.Low : "High" in value ? Priority.High : "Medium" in value ? Priority.Medium : "Urgent" in value ? Priority.Urgent : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Session>): Array<Session> {
    return value.map((x)=>from_candid_Session_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n20(_uploadFile, _downloadFile, x));
}
function to_candid_BlockType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlockType): _BlockType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_CalendarEvent_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CalendarEvent): _CalendarEvent {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Priority_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Session_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Session): _Session {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_TaskState_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskState): _TaskState {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Task_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Task): _Task {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    effortTracks: bigint;
    name: string;
    createdAt: bigint;
    deadline?: bigint;
    state: TaskState;
    notes?: string;
    priority: Priority;
}): {
    effortTracks: bigint;
    name: string;
    createdAt: bigint;
    deadline: [] | [bigint];
    state: _TaskState;
    notes: [] | [string];
    priority: _Priority;
} {
    return {
        effortTracks: value.effortTracks,
        name: value.name,
        createdAt: value.createdAt,
        deadline: value.deadline ? candid_some(value.deadline) : candid_none(),
        state: to_candid_TaskState_n11(_uploadFile, _downloadFile, value.state),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        priority: to_candid_Priority_n13(_uploadFile, _downloadFile, value.priority)
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduledDate: bigint;
    blockType: BlockType;
    taskId: bigint;
    trackPosition: bigint;
}): {
    scheduledDate: bigint;
    blockType: _BlockType;
    taskId: bigint;
    trackPosition: bigint;
} {
    return {
        scheduledDate: value.scheduledDate,
        blockType: to_candid_BlockType_n5(_uploadFile, _downloadFile, value.blockType),
        taskId: value.taskId,
        trackPosition: value.trackPosition
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalTracks: bigint;
    startedAt: bigint;
    pauseCount: bigint;
    endedAt?: bigint;
    tracksCompleted: bigint;
    playlistId: string;
    score: bigint;
    taskId: bigint;
    playlistName: string;
    completedWithinSession: boolean;
}): {
    totalTracks: bigint;
    startedAt: bigint;
    pauseCount: bigint;
    endedAt: [] | [bigint];
    tracksCompleted: bigint;
    playlistId: string;
    score: bigint;
    taskId: bigint;
    playlistName: string;
    completedWithinSession: boolean;
} {
    return {
        totalTracks: value.totalTracks,
        startedAt: value.startedAt,
        pauseCount: value.pauseCount,
        endedAt: value.endedAt ? candid_some(value.endedAt) : candid_none(),
        tracksCompleted: value.tracksCompleted,
        playlistId: value.playlistId,
        score: value.score,
        taskId: value.taskId,
        playlistName: value.playlistName,
        completedWithinSession: value.completedWithinSession
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskState): {
    Overtime: null;
} | {
    InProgress: null;
} | {
    Completed: null;
} | {
    NotStarted: null;
} {
    return value == TaskState.Overtime ? {
        Overtime: null
    } : value == TaskState.InProgress ? {
        InProgress: null
    } : value == TaskState.Completed ? {
        Completed: null
    } : value == TaskState.NotStarted ? {
        NotStarted: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} | {
    Urgent: null;
} {
    return value == Priority.Low ? {
        Low: null
    } : value == Priority.High ? {
        High: null
    } : value == Priority.Medium ? {
        Medium: null
    } : value == Priority.Urgent ? {
        Urgent: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlockType): {
    Playlist: null;
} | {
    Single: null;
} {
    return value == BlockType.Playlist ? {
        Playlist: null
    } : value == BlockType.Single ? {
        Single: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
